project:
  type: website

website:
  title: "Math 378 Final Project Francoeur"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - eda.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

