---
title: "Penguins EDA"
format:
  html:
    code-fold: true
---

## Penguin Size and Mass by Sex and Species

```{r}
install.packages("dplyr")
install.packages("ggplot2")
```

```{r}
library(palmerpenguins)
library(dplyr)
library(dbplyr)
library(ggplot2)

df <- palmerpenguins::penguins
```

```{r}
# Create a scatter plot
ggplot(df, aes(x = bill_length_mm, y = body_mass_g, color = sex)) +
  geom_point() +
  labs(x = "Bill Length (mm)", y = "Body Mass (g)", color = "Sex") +
  ggtitle("Penguin Size by Sex") +
  theme_minimal()
```

```{r}
df %>%
  group_by(species, sex) %>%
  summarise(
    across(
      where(is.numeric), 
      \(x) mean(x, na.rm = TRUE)
      )
    ) %>%
  knitr::kable()
```

## Penguin Size vs Mass by Species

```{r}
df %>%
  ggplot(aes(x = bill_length_mm, y = body_mass_g, color = species)) +
  geom_point() + 
  geom_smooth(method = "lm")
```

```{r}
install.packages("DBI")
library(DBI)
```

```{r}
con <- DBI::dbConnect(duckdb::duckdb(), dbdir = "my-db.duckdb")
#DBI::dbWriteTable(con, "penguins", palmerpenguins::penguins)
DBI::dbDisconnect(con)
```

```{python}
import duckdb
from palmerpenguins import penguins
```

```{r}
install.packages("tidyselect")
```

```{r}
con <- DBI::dbConnect(
  duckdb::duckdb(), 
  dbdir = "my-db.duckdb"
  )
df <- dplyr::tbl(con, "penguins")
DBI::dbDisconnect(con, shutdown = TRUE)
```
